name: Update NPM Dependencies

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # This schedule runs the action daily at midnight
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CUSTOM_GH_TOKEN}}

      - name: Run NPM Dependency Update Action
        uses: itamarsher/test_action@main
